language: python
python:
  - 3.2
  - 3.3
  - 3.4
  - 3.5

install:
  - pip install .

script:
  - python setup.py bdist_wheel
before_deploy:
  - python setup.py bdist_wheel

deploy:
  provider: releases
  api_key: $CI_USER_TOKEN
  file: "./dist/*.whl"
  skip_cleanup: true
  on:
    tags: true
